### ISSUE TITLE
device provisioning scenario: User joins via the CLI

### ISSUE THREAD

**Issue by patrickxb** [keybase/go#111]
Ongoing checklist of subtasks:
  - [x] Keybase Site changes
    - [x] Device Add/List API (keybase/keybase#208)
    - [x] Clean up `security.iced`w/r/t defunct key fields, and new key materials (keybase/keybase#209)
    - [x] Change `key/fetch_private` to also fetch per-device secret halves (keybase/keybase#210)
  - [x] ComputedKeyFamily changes
    - [x] We need device IDs in computed keys
    - [x] Keep pointers from Sibkey to active encryption subkey
    - [x] Is it a DetKey or not?
  - [x] Client/Daemon changes
    - [x] Refactor cmd_signup, SignupEngine to have multiple steps
    - [x] Implement device add
    - [x] Implement provisioning

From: https://keybase.io/admin-docs/device-provisioning/ux

**Comment by maxtaco** [comment]
@patrickxb, I thought we'd make a "pseudo-device" for the Web browser, that will be synonymous with DetKeys.  Do you think that could work?

**Comment by maxtaco** [comment]
Also we should have a more explicit mapping from sibkey to subkey.  See keybase/keybase#211

**Comment by patrickxb** [comment]
@maxtaco pseudo-device sounds good.  Should work.

**Comment by patrickxb** [comment]
device provisioning via cli signup working.  merged to master.
