### ISSUE TITLE
OSX Main Screen RPC-API Checklist

### ISSUE THREAD

**Issue by gabriel** [keybase/go#155]
For the admin docs, osx client, main screen functionality needs in the RPC API:

- [ ] User image in record [#101](https://github.com/keybase/go/issues/101)
- People
  - [ ] List of users a user is tracking
  - [ ] List of users tracking a user
- Devices
  - [ ] List (image, name, last_used)
  - [ ] Actions (revoke?, add)
- Folders/favorites
  - [ ] List  

Lower priority:
- People
  - [ ] Recent users I've interacted with  
  - [ ] Recommended users (to track)
  - [ ] Search
- Folders/favorites:
  - [ ] List recent

**Comment by maxtaco** [comment]
What do you have in mind for Devices.add?

**Comment by maxtaco** [comment]
Forgot password: there isn't a great story here.  You're basically shit out of luck if you forget your password, and you've lost access to all of your private keys.  You need to nuke your account and start over.  We could have the user generate a "backup passphrase", which maps to a detkey sibkey.

Also, logins should be public key login for now, so users should only need to login via passphrase once. I'm sure a lot of this needs tweaking, so let's figure out what's required...

**Comment by maxtaco** [comment]
Listing devices: last-used currently isn't implemented.  Do we take the server's word on this?  Is there a potential metadata leakage we're not happy with?  Should we be signing sigchain links here instead?  Undecided...

**Comment by gabriel** [comment]
I guess device add doesn't make sense yet... maybe in a bit when say to want to login on iPhone and you need a QR code or passphrase "TONGUE RAG BOON ICE MAN CHAI SALAD" to authenticate this new device (see https://keybase.io/admin-docs/device-provisioning/ux). Will move to low priority.

**Comment by gabriel** [comment]
For example if you go into google app passwords you can see when a password was last used, which is helpful or insightful if there is a really old password that hasn't been used in a long time you should probably revoke it... This feature can wait till later though?

Or I could use the time the device last added to the sig chain?

**Comment by gabriel** [comment]
(re: forgot password) yeah this isn't a priority at all, gonna remove it from the list

**Comment by maxtaco** [comment]
(re: device last used).  Ok, we can definitely show when the device was last used to sign a sigchainlink as you say.  We can supplement that data to say when the key was last used for a login or kbfs, let's say.  OK, we can get that done.
